### ISSUE TITLE
UIButton事件请教

### ISSUE THREAD

**Issue by fjhhjf** [JakeLin/Todo#4]
非常感谢Jake的教程，在此有个小的疑问：
对于新建todo项的页面中，UIButton“确定”有一个tapped事件及unwind事件，为什么我写的程序里总是先执行unwind的代码，然后才执行tapped中的代码，请问哪里可以设置顺序吗？

**Comment by JakeLin** [comment]
应该call unwind in code

[self performSegueWithIdentifier:@"unwindToViewController1" sender:self];

2015-07-15 0:16 GMT+10:00 fjhhjf <notifications@github.com>:

**Comment by fjhhjf** [comment]
非常感谢！！！

发自我的 iPhone
